
version: 2

updates:
  - package-ecosystem: bundler
    directory: /project_a
    vendor: true
    schedule:
      interval: daily
    labels:
      - dependencies
    allow:
      - dependency-name: sorbet*
        dependency-type: indirect
  - package-ecosystem: bundler
    directory: /project_b
    vendor: true
    schedule:
      interval: daily
    labels:
      - dependencies
    allow:
      - dependency-name: sorbet*
        dependency-type: indirect
