source "https://rubygems.org"

# Specify your gem's dependencies in project_a.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"

# Using Sorbet because it's updated almost daily
gem "sorbet", "0.5.6500", group: :development
gem "sorbet-runtime", "0.5.6483"
